nelmio_api_doc:
    use_validation_groups: true
    documentation:
        info:
            title: 'Waxbill API'
            description: 'Waxbill API'
            version: '1.0.0'
    areas:
        path_patterns:
            - ^/api(?!/docs$)
    models:
        names:
            - { alias: TagRequest, type: App\Entity\Tag, groups: [ write ] }
